name: Gravitee.io APIM
description: Gravitee.io - Open Source API Management Solution
version: v1-rancher
category: API Management
licence : Apache Licence, version 2
maintainer: Sébastien Renno <sebastien.renno@leansys.fr>
